
package Scenarios;

import Interfaces.IStructure;
import Factories.*;
import Observers.*;

import javax.swing.*;
import java.awt.*;


public class Level6 extends Level {

    public Level6() {
        super();
        initScenario();

    }

    public void initScenario() {

        labelLevel = new JLabel();

        setStructureFactory(new EagleStructureFactory());
        setEagle(returnStructureFactory().createStructure(new Point(384, 768)));

        setStructureFactory(new BrickStructureFactory());

        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 32)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 32)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 0)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 0)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 448)));

        setStructureFactory(new WallStructureFactory());

        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 672)));

        setStructureFactory(new WaterStructureFactory());

        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 256)));

        setStructureFactory(new GrassStructureFactory());

        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 512)));

        returnPanelGame().add(returnEagle().getLabel());

        returnTanksLeft().add(new TankObserver(new Point(925, 270)));
        returnTanksLeft().add(new TankObserver(new Point(890, 270)));
        returnTanksLeft().add(new TankObserver(new Point(960, 235)));
        returnTanksLeft().add(new TankObserver(new Point(925, 235)));
        returnTanksLeft().add(new TankObserver(new Point(890, 235)));
        returnTanksLeft().add(new TankObserver(new Point(960, 200)));
        returnTanksLeft().add(new TankObserver(new Point(925, 200)));
        returnTanksLeft().add(new TankObserver(new Point(890, 200)));
        returnTanksLeft().add(new TankObserver(new Point(960, 165)));
        returnTanksLeft().add(new TankObserver(new Point(925, 165)));
        returnTanksLeft().add(new TankObserver(new Point(890, 165)));
        returnTanksLeft().add(new TankObserver(new Point(960, 130)));
        returnTanksLeft().add(new TankObserver(new Point(925, 130)));
        returnTanksLeft().add(new TankObserver(new Point(890, 130)));
        returnTanksLeft().add(new TankObserver(new Point(960, 95)));
        returnTanksLeft().add(new TankObserver(new Point(925, 95)));
        returnTanksLeft().add(new TankObserver(new Point(890, 95)));
        returnTanksLeft().add(new TankObserver(new Point(960, 60)));
        returnTanksLeft().add(new TankObserver(new Point(925, 60)));
        returnTanksLeft().add(new TankObserver(new Point(890, 60)));
        setBulletCounter(new BulletObserver(new Point(940, 780)));
        setCardCounter(new CardObserver(new Point(940, 740)));

        labelLevel.setText("6");
        labelLevel.setFont(new Font("Pixel NES", Font.PLAIN, 40));
        labelLevel.setForeground(Color.black);
        returnPanelWindow().add(labelLevel);
        labelLevel.setBounds(940, 505, 35, 35);

        for (IStructure structure : returnStructures())
            returnPanelGame().add(structure.getLabel());

        for (TankObserver tank : returnTanksLeft())
            returnPanelWindow().add(tank.getLabel());

        returnPanelWindow().add(returnCardCounter().getLabel());
        returnPanelWindow().add(returnBulletCounter().getLabel());

        returnPanelWindow().add(returnPanelGame());
        returnPanelGame().setBounds(0, 0, 832, 832);

    }

    JLabel labelLevel;
}
