
package Scenarios;

import Interfaces.IStructure;
import Factories.*;
import Observers.*;

import javax.swing.*;
import java.awt.*;

public class Level1 extends Level {

    public Level1() {
        super();
        initScenario();
    }

    public void initScenario() {

        labelLevel = new JLabel();

        setStructureFactory(new EagleStructureFactory());
        setEagle(returnStructureFactory().createStructure(new Point(384, 768)));

        setStructureFactory(new BrickStructureFactory());

        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 608)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(352, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(320, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 288)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 544)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(448, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(480, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 576)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 224)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 448)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 480)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(192, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(224, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 512)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(416, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(288, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 256)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(608, 128 )));
        returnStructures().add(returnStructureFactory().createStructure(new Point(576, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(544, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(512, 96)));

        setStructureFactory(new WallStructureFactory());

        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 192)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(256, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(384, 320)));

        setStructureFactory(new WaterStructureFactory());

        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 320)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 352)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 416)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 384)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 320)));

        setStructureFactory(new GrassStructureFactory());

        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 0)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 32)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 0)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 32)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 32)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 32)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(160, 0)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(128, 0)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 160)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 128)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 32)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 32)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 0)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 0)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 96)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 64)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(32, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(0, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(96, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(64, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 672)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(800, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(768, 640)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 736)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 704)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(672, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(640, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 768)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(736, 800)));
        returnStructures().add(returnStructureFactory().createStructure(new Point(704, 800)));

        returnPanelGame().add(returnEagle().getLabel());

        returnTanksLeft().add(new TankObserver(new Point(925, 270)));
        returnTanksLeft().add(new TankObserver(new Point(890, 270)));
        returnTanksLeft().add(new TankObserver(new Point(960, 235)));
        returnTanksLeft().add(new TankObserver(new Point(925, 235)));
        returnTanksLeft().add(new TankObserver(new Point(890, 235)));
        returnTanksLeft().add(new TankObserver(new Point(960, 200)));
        returnTanksLeft().add(new TankObserver(new Point(925, 200)));
        returnTanksLeft().add(new TankObserver(new Point(890, 200)));
        returnTanksLeft().add(new TankObserver(new Point(960, 165)));
        returnTanksLeft().add(new TankObserver(new Point(925, 165)));
        returnTanksLeft().add(new TankObserver(new Point(890, 165)));
        returnTanksLeft().add(new TankObserver(new Point(960, 130)));
        returnTanksLeft().add(new TankObserver(new Point(925, 130)));
        returnTanksLeft().add(new TankObserver(new Point(890, 130)));
        returnTanksLeft().add(new TankObserver(new Point(960, 95)));
        returnTanksLeft().add(new TankObserver(new Point(925, 95)));
        returnTanksLeft().add(new TankObserver(new Point(890, 95)));
        returnTanksLeft().add(new TankObserver(new Point(960, 60)));
        returnTanksLeft().add(new TankObserver(new Point(925, 60)));
        returnTanksLeft().add(new TankObserver(new Point(890, 60)));
        setBulletCounter(new BulletObserver(new Point(940, 780)));
        setCardCounter(new CardObserver(new Point(940, 740)));

        labelLevel.setText("1");
        labelLevel.setFont(new Font("Pixel NES", Font.PLAIN, 40));
        labelLevel.setForeground(Color.black);
        returnPanelWindow().add(labelLevel);
        labelLevel.setBounds(940, 505, 35, 35);

        for (IStructure structure : returnStructures())
            returnPanelGame().add(structure.getLabel());

        for (TankObserver tank : returnTanksLeft())
            returnPanelWindow().add(tank.getLabel());

        returnPanelWindow().add(returnCardCounter().getLabel());
        returnPanelWindow().add(returnBulletCounter().getLabel());

        returnPanelWindow().add(returnPanelGame());
        returnPanelGame().setBounds(0, 0, 832, 832);

    }

    JLabel labelLevel;

}
